version: '3.9'

services:
  telegram-bot:
    build: .
    env_file: .env
    volumes:
      - core/images/goldenLikePhoto.jpg:/core/images/goldenLikePhoto.jpg
    depends_on:
      - sqlite-db

  sqlite-db:
    image: tiangolo/uwsgi-nginx-flask:python3.9
    environment:
      SQLITE_DATABASE_URI: sqlite:///goldenLike.db
