version: '3.9'

services:
  telegram-bot:
    build: .
    env_file: .env
    depends_on:
      - sqlite-db

  sqlite-db:
    image: tiangolo/uwsgi-nginx-flask:python3.9
    environment:
      SQLITE_DATABASE_URI: sqlite:///goldenLike.db
